name: py-core-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ve-analiz:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Çek (Checkout)
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: uv Kurulumu
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Bağımlılıkları Yükle
        run: uv sync

      - name: Ruff ile Statik Analiz (Linter)
        run: uv run ruff check .

      - name: Mypy ile Tip Kontrolü
        run: uv run mypy src